controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# index:
#     path: /
#     controller: App\Controller\HomeController::index
# actualite:
#     path: /actualite/
#     controller: src\Controller\ActualiteController::index
# commentaire:
#     path: /commentaire/
#     controller: src\Controller\CommentaireController::index